<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Members/Site1.Master" CodeBehind="admin.aspx.cs" Inherits="MyPrograms.Members.admin" %>

<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
    <link href="/CSS/Admin.css" rel="stylesheet" />

</asp:Content>
<asp:Content ID="HeaderTitle" ContentPlaceHolderID="HeaderText" runat="server">Admin Page</asp:Content>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <!DOCTYPE html>
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server"></telerik:RadScriptManager>
    <div id="MainTables">
        <div id="Dropdown">
            <asp:Label ID="Label1" runat="server" Text="Tables"></asp:Label>
            <br /><br />
            <telerik:RadComboBox ID="Droplist_Tables" runat="server" Skin="Glow"></telerik:RadComboBox>
        </div>
        <div id="fetchDiv">
            <telerik:RadButton ID="fetchButton" runat="server" Text="Fetch" OnClick="fetchButton_Click"></telerik:RadButton>
        </div>
    </div>

    <div id="myGrid">
        <telerik:RadGrid ID="tableGrid" runat="server" OnItemCommand="tableGrid_ItemCommand" GroupPanelPosition="Top" Skin="Glow" CellSpacing="-1" GridLines="Both" AutoGenerateDeleteColumn="True">
<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
            <ValidationSettings CommandsToValidate="PerformInsert,Update,Delete" />
            <MasterTableView EditMode="PopUp">
            </MasterTableView>
        </telerik:RadGrid>
    </div>

    <div id="myDetails">

        <asp:DetailsView ID="myDetailsView" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" Height="50px" Width="125px">
            <AlternatingRowStyle BackColor="White" />
            <CommandRowStyle BackColor="#C5BBAF" Font-Bold="True" />
            <EditRowStyle BackColor="#7C6F57" />
            <FieldHeaderStyle BackColor="#D0D0D0" Font-Bold="True" />
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#E3EAEB" />
        </asp:DetailsView>

    </div>


</asp:Content>
